name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ ouinon123456789 }}
            password: ${{ rigeKfA?hg8Ymy3? }}
            registry: docker.io
            repository: ouinon123456789/cd
            tag_with_sha: true
