name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: ouinon123456789/cd
            tag_with_sha: true
            
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }
